In [0]:
import numpy as np
import pandas as pd
from sklearn import datasets

In [0]:
class linear_regressor(object):
    
    def __init__(self, params):
        self._params = params 
        self._eta = self._params['eta']
        self._iterations = self._params['iterations']
        
    def gradient_descent(self, x, y, eta, theta):
        
        m = len(x)
        
        gradients = (2 / m) * x.T.dot(x.dot(theta) - y)
        theta -= eta * gradients 
        
        return theta 
    
    def train(self, x_trn, y_trn):
        
        sample_size, feature_size = x_trn.shape
        
        theta = np.zeros((1, feature_size)).T
        
        for i in range(self._iterations):
            theta = self.gradient_descent(x_trn, y_trn, self._eta, theta)
            
        return theta

In [0]:
class ridge_regressor(object):
    
    def __init__(self, params):
        self._params = params 
        self._eta = self._params['eta']
        self._alpha = self._params['alpha']
        self._iterations = self._params['iterations']
        
    def gradient_descent(self, x, y, eta, alpha, theta):
        
        m = len(x)
        
        reg_gradients = theta
        gradients = (2 / m) * x.T.dot(x.dot(theta) - y) + alpha * reg_gradients
        theta -= eta * gradients 
        
        return theta 
    
    def train(self, x_trn, y_trn):
        
        sample_size, feature_size = x_trn.shape
        
        theta = np.zeros((1, feature_size)).T
        
        for i in range(self._iterations):
            theta = self.gradient_descent(x_trn, y_trn, self._eta, self._alpha, theta)
            
        return theta

In [0]:
class lasso_regressor(object):
    
    def __init__(self, params):
        self._params = params 
        self._eta = self._params['eta']
        self._alpha = self._params['alpha']
        self._iterations = self._params['iterations']
        
    def gradient_descent(self, x, y, eta, alpha, theta):
        
        m = len(x)
        
        reg_gradients = np.array([1 if i > 0 else -1 if i < 0 else 0 for i in theta]).reshape(len(theta), 1)
        gradients = (2 / m) * x.T.dot(x.dot(theta) - y) + alpha * reg_gradients
        theta -= eta * gradients 
        
        return theta 
    
    def train(self, x_trn, y_trn):
        
        sample_size, feature_size = x_trn.shape
        
        theta = np.zeros((1, feature_size)).T
        
        for i in range(self._iterations):
            theta = self.gradient_descent(x_trn, y_trn, self._eta, self._alpha, theta)
            
        return theta

In [0]:
lr = linear_regressor({'iterations':100, 'eta':0.01})
ridge = ridge_regressor({'iterations':100, 'eta':0.01, 'alpha':0.5})
lasso = lasso_regressor({'iterations':100, 'eta':0.01, 'alpha':0.5})

In [0]:
X = np.random.randn(100, 3)
Y = np.random.randn(100, 1)

In [0]:
lr.train(X, Y)

array([[ 0.08023783],
       [-0.00207789],
       [ 0.0957701 ]])

In [0]:
ridge.train(X, Y)

array([[ 0.06718784],
       [-0.00214848],
       [ 0.08147307]])

In [0]:
lasso.train(X, Y)

array([[0.00195513],
       [0.0009653 ],
       [0.00691431]])

In [0]:
class logistic_regressor(object):
    
    def __init__(self, params):
        self._params = params 
        self._eta = self._params['eta']
        self._iterations = self._params['iterations']
        
    @staticmethod    
    def sigmoid(x):
        return 1 / (1 + np.exp(-x))        
        
    def gradient_descent(self, x, y, eta, theta):
        
        m = len(x)
        
        z = sigmoid(np.dot(x, theta))
        gradients = np.dot(x.T, z - y) / m
        theta -= eta * gradients
        
        return theta 
    
    def train(self, x_trn, y_trn):
        
        sample_size, feature_size = x_trn.shape
        
        theta = np.zeros((1, feature_size)).T
        
        for i in range(self._iterations):
            theta = self.gradient_descent(x_trn, y_trn, self._eta, theta)
            
        return theta

In [0]:
log_reg = logistic_regressor({'iterations':100, 'eta':0.01})

In [0]:
iris = datasets.load_iris()
x = iris.data[:, :2]
y = ((iris.target != 0) * 1)
y = y.reshape(len(y), 1)

In [43]:
log_reg.train(x, y)

array([[ 0.21408372],
       [-0.14248542]])